### PR TITLE
It's a README

### PR DESCRIPTION
**Pull request by jamiew**
It's a README

### CODE REVIEW

**Comment by ckolderup** [comment]
Hi Jamie, thanks for getting this started! I have a few edits I'd like to make sometime in the next day or two when I have a free moment at home; in part to reflect things are misleading based on what I've checked into the repo (I think people should be using rbenv, based on what I've read and @hoverbird's suggestion, and it's time for me to cut the cord with rvm).

Anyway, I'll try to figure out how to add on some changes here (I can do that, right?) and we can merge once those're done.

**Comment by jamiew** [comment]
Cool, I just wrote up what I needed to do to get the app running. 

I don't think you can append changes to this pull request (especially because I didn't use a topic branch #RUHROH) but you could merge this and iterate on updates, or just close this and re-do it all later -- otherwise this'll start including other changes I make in my fork's master

**Comment by ckolderup** [comment]
Haha, okay, I better merge it in really quickly then and I'll update things from my side!

**Comment by jamiew** [comment]
:tableflip:

**Pull request merged**
