### PR TITLE
Leaf Tests

### PR DESCRIPTION
**Pull request by hoverbird**
First tests for leaf game.  Need to drop chromedriver somewhere in your path in order to run: 
http://code.google.com/p/chromium/downloads/detail?name=chromedriver_mac_18.0.995.0.zip

Haven't added new functionality (i.e. win conditions yet, wanted to get base testing environment set up first.

### CODE REVIEW

**Comment by ckolderup** [comment]
Looks good overall. We'll eventually need to change /play to look up a game based on the slug, but we need an interface to actually start loading games into the db to do that. I've got a big project launch at work this Wednesday, and I'm hoping after that I can get back to working on the style-less interface for browsing & creating games.

Also, would you be okay with me changing play.erb into play.haml at some point? It'd be nice if we could stick with one templating language.

**Comment by hoverbird** [comment]
Re: making the slug actually look up a game in the DB- yes, sounds great.

As for templates, I'm all for standardizing on one language, though I'm biased towards something HTML-like such as Mustache or ERB. Unless everyone on the team already knows HAML, I'm skeptical about the value of adding another syntax to our stack given that all the designers and coders are super-comfortable with HTML.

**Comment by ckolderup** [comment]
I started out with HAML because I had discussed it in the chat room with David and Joe before and they had indicated that they liked it. David has worked with it a decent amount and Joe said he had been looking for a reason to.

**Comment by hoverbird** [comment]
Cool, sounds like the discussion already happened. I'm fine with standardizing on HAML.

**Comment by irondavy** [comment]
I'm happy to learn whatever is best for the project. If it's no difference, I am a really big fan of HAML.

**Comment by hoverbird** [comment]
It makes no difference, once one knows HTML and HAML, in terms of developer speed etc.  I always vote for "write what you love", and it sounds like folks really like HAML. I've never dug in with it myself because it didn't seem like a huge improvement over existing standards, but I admire how terse and expressive it can be. If one of you gents could change play.erb into HAML so I can get an idea of what good style looks like, I'm sure I'll pick it up quickly (and probably be a convert, before too long).

**Comment by hoverbird** [comment]
OK! So we have passing selenium specs now, and a new test case that meets @ardubs simple obstacle-hint-win scenario (it's called (leaf_user_spec).  Can some folks check this branch out locally and kick the tires? You should be able to run specs by doing "bundle exec rspec path/to/spec".  The relevant specs are in spec/games.

There was a fair bit of refactoring to support generic things like "fire this event after this action" and "before doing this action, check this property" and it's far from complete, but I wanted to see what you guys think about this direction.  Feel free to shoot any bug reports or questions to patrick@twitter.com (I don't get github notifications)

**Pull request merged**
